AmazingRace/Models/Staff.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AmazingRace.Models
{
    public class Staff
    {
        [Required(ErrorMessage ="Staff ID is Mandatory")]
        public int StaffID { get; set; }
        [Required(ErrorMessage = "Staff Name is Mandatory")]
        [DisplayName("Staff Name ")]
        public string StaffName { get; set; }
        [DisplayName("Email ID ")]
        [Required(ErrorMessage = "Email ID is Mandatory")]
        public string EmailID { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Password is Required")]
        public string Password { get; set; }
        [NotMapped]
        [DisplayName("Confirm Password")]
        [Required(ErrorMessage = "Re-Enter your Password")]
        [Compare("Password",ErrorMessage ="Password doesn't match, Type Again !!" )]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }

    }
}

AmazingRace/Models/UserActiviation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AmazingRace.Models
{
    public class UserActiviation
    {
        public int userId { get; set; }
        public string ActivationCode { get; set; }
    }
}

AmazingRace/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AmazingRace.DAL;
using AmazingRace.Models;
using System.Net;
using System.Net.Mail;

namespace AmazingRace.Controllers
{
    public class HomeController : Controller
    {
        private AmazingRaceContext db = new AmazingRaceContext();

        [HttpGet]
        public ActionResult Index()
        {
            return View(new Staff());
        }

        [HttpPost]
        public ActionResult Index(Staff staff)
        {
            return View(staff);
        }


        [HttpGet]
        public ActionResult SignUp()
        {
            return View(new Staff());
        }

        [HttpPost]
        public ActionResult SignUp(Staff staff)
        {
            db.Staffs.Add(staff);
            db.SaveChanges();
            SendActivationEmail(staff);
            return View("Success");

        }

        private void SendActivationEmail(object user)
        {
           
}
    }
}

AmazingRace/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AmazingRace.DAL;
using AmazingRace.Models;

namespace AmazingRace.Controllers
{
    public class StaffController : Controller
    {
        private AmazingRaceContext db = new AmazingRaceContext();
    
        
        public ActionResult StaffHomePage(Staff staff)
        {

          var myUser = db.Staffs
         .FirstOrDefault(u => u.EmailID == staff.EmailID
                      && u.Password == staff.Password);

            if (myUser != null)   
            {
                return View();
            }

            else
            {
                return RedirectToAction("Error");
            }
            
        

        }
    }
}

AmazingRace/Views/Home/Index.cshtml
@model AmazingRace.Models.Staff

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@using (Html.BeginForm("StaffHomePage","Staff")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Staff</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.LabelFor(model => model.EmailID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sign In" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AmazingRace/Views/Home/SignUp.cshtml
@model AmazingRace.Models.Staff

@{
    ViewBag.Title = "SignUp";
}

<h2>SIGN UP</h2>
<br>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StaffName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StaffName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StaffName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sign Up" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AmazingRace/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AmazingRace/Views/Staff/StaffHomePage.cshtml
@{
    ViewBag.Title = "StaffHomePage";
}

<h2>StaffHomePage</h2>